//! `mapbox completion <shell>` — a completion script for the built tree.
//!
//! The script is generated by `clap_complete` from the same `Command` this
//! process assembled, so it cannot describe a different CLI than the binary
//! that printed it: an operation `Operation::is_exposed` withholds, a
//! flag-gated command a release build leaves out (`feature_flags`), and a
//! service a spec sync added yesterday are all handled by not being special
//! cases at all. `a_withheld_operation_is_absent_from_every_shell` in
//! `tests/completion.rs` holds the first of those.
//!
//! Three decisions behind the shape of this, each of which keeps being
//! re-asked:
//!
//! - **Four shells**, named rather than taken from `clap_complete::Shell` by
//!   `value_variants()`. That enum also carries Elvish, and offering a shell
//!   nobody here has sourced a script in would be claiming something untested
//!   — `SHELLS` is the list this repo verifies, and adding to it means adding
//!   to `tests/completion.rs` in the same commit.
//! - **stdout, not a file this CLI chose.** Every shell keeps its completions
//!   somewhere different, several allow more than one place, and the choice
//!   depends on a framework this CLI cannot see (`bash-completion`, oh-my-zsh,
//!   `fish_complete_path`). Printing hands that decision back to the person
//!   who knows it, and makes the command composable — `> file`, `source <(…)`,
//!   piped into `sudo tee`. Nothing is written to disk and no shell config is
//!   edited.
//! - **Commands and flags only.** Completing a style id, a tileset id or a
//!   username would need a network call and a live token in the middle of a
//!   keystroke; `clap_complete`'s dynamic mode is behind an unstable feature,
//!   and neither is in scope here.
//!
//! The installers were left out of it for the same reason as the second
//! decision above: `scripts/install.sh` and `install.ps1` neither ask about
//! completions nor write one, so finding a shell's completion directory stays
//! nobody's job here.
//!
//! The script itself is the result, so it goes to stdout whole and unwrapped:
//! `--output json` cannot apply to it any more than it applies to a `.mvt`
//! tile — see [`warn_output_ignored`], and this repo's output-contract
//! exemption list.

use std::io::{self, Write};

use anyhow::{Context, Result};
use clap::builder::PossibleValuesParser;
use clap::parser::ValueSource;
use clap::{Arg, ArgMatches, Command};
use clap_complete::Shell;

pub const COMMAND: &str = "completion";

/// The positional's id, and the value name its help renders.
const SHELL_ARG: &str = "shell";

/// The shells this CLI claims, and the `clap_complete` generator for each.
///
/// Deliberately not `Shell::value_variants()`: that would add Elvish for
/// free, and "for free" is the problem — every name here is one
/// `tests/completion.rs` generates a script for and checks, and one
/// a maintainer-only test harness loads in the real shell. A shell added
/// to this list without both is a claim nothing backs.
const SHELLS: &[(&str, Shell)] = &[
    ("bash", Shell::Bash),
    ("zsh", Shell::Zsh),
    ("fish", Shell::Fish),
    ("powershell", Shell::PowerShell),
];

/// The value the caller typed, resolved to a generator.
fn shell_named(name: &str) -> Option<Shell> {
    SHELLS
        .iter()
        .find_map(|(spelling, shell)| (*spelling == name).then_some(*shell))
}

fn shell_names() -> Vec<&'static str> {
    SHELLS.iter().map(|(name, _)| *name).collect()
}

pub fn command() -> Command {
    Command::new(COMMAND)
        .about("Print a shell completion script for `mapbox`")
        .long_about(
            "Print a completion script for one shell on stdout.\n\n\
             The script is generated from this binary's own command tree, so it completes \
             exactly the services, operations and flags this build has — nothing is \
             maintained by hand and nothing can fall behind a spec sync. It completes \
             command and flag names; values such as style ids or usernames are not \
             completed, since that would mean a request and a token mid-keystroke.\n\n\
             Nothing is written to disk: redirect it where your shell looks, or source it \
             directly. `--output` does not apply — the script is the result.",
        )
        .arg(
            Arg::new(SHELL_ARG)
                .required(true)
                .value_name("SHELL")
                .value_parser(PossibleValuesParser::new(shell_names()))
                .help("The shell to generate for"),
        )
}

/// Warns that `--output` stops here, for the reason `tilesets_cli` warns
/// about the same flag.
///
/// Only when it was typed on this command line. `MAPBOX_OUTPUT` is exported
/// once and applies to everything, so warning on it would nag at a caller who
/// set it for entirely different commands — the same line
/// `tilesets_cli::warn_output_ignored` draws, and for the same reason.
///
/// It stays quiet for `auto` too, and that is the case that matters: `mapbox
/// completion bash > mapbox.bash` is the ordinary use, `auto` resolves a
/// redirect to `json`, and a warning on the one invocation everybody types
/// would be noise on the happy path.
pub fn warn_output_ignored(matches: &ArgMatches) {
    if matches.value_source(crate::output::ARG) != Some(ValueSource::CommandLine) {
        return;
    }
    eprintln!(
        "Warning: `--{}` is not honoured by `{COMMAND}` — a completion script is a shell \
         script, and wrapping it in an envelope would leave it unsourceable.",
        crate::output::ARG
    );
}

/// Prints the script for the shell named on the command line.
///
/// `app` is the built tree — the same copy `--schema` and `generate-skills`
/// read. `clap_complete` needs it mutable (it builds the tree out before
/// walking it), and this is the one caller that cannot hand over ownership,
/// so it clones. The clone costs one command tree on a command that is about
/// to exit, and buys `run`'s single `&Command` staying whole for everything
/// after it.
pub fn run(app: &Command, matches: &ArgMatches) -> Result<()> {
    let name = matches
        .get_one::<String>(SHELL_ARG)
        .expect("the shell positional is required");
    let shell = shell_named(name)
        .unwrap_or_else(|| panic!("clap accepted `{name}`, which is not in SHELLS"));

    let mut app = app.clone();
    // The binary is `mapbox`, whatever the crate is called and whatever the
    // file on disk was renamed to. A script generated under another name
    // would install cleanly and complete nothing.
    let bin_name = app.get_name().to_string();

    // Rendered into memory first, and that is not a style choice.
    // `clap_complete::generate` unwraps every write, so handing it the real
    // stdout turns `mapbox completion bash | head` — a pipe closing early,
    // which is what `head`, `less` and a shell's `source <(…)` all do — into
    // a Rust panic with a backtrace note, on a command that had already
    // produced its whole answer. A `Vec` cannot fail that way, and the
    // ~280 KB it costs belongs to a process that is about to exit.
    let mut script: Vec<u8> = vec![];
    clap_complete::generate(shell, &mut app, bin_name, &mut script);

    // Straight to stdout rather than through `output::emit`: the script is
    // the result, and there is no rendering of it that is not itself.
    let mut out = io::stdout().lock();
    match out.write_all(&script).and_then(|()| out.flush()) {
        // A reader that stopped reading is `head`'s ordinary behaviour, not a
        // failure to report: the error envelope would be the only thing left
        // on a terminal after a command that did exactly what was asked.
        Err(e) if e.kind() == io::ErrorKind::BrokenPipe => Ok(()),
        other => other.context("could not write the completion script to stdout"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The tree these unit tests complete against. `build_app` needs the
    /// parsed specs, which is a whole binary's worth of work for questions
    /// that are about this module.
    fn tiny_app() -> Command {
        Command::new("mapbox")
            .subcommand(Command::new("styles").subcommand(Command::new("get-style")))
            .subcommand(command())
    }

    fn generate(shell: Shell) -> String {
        let mut app = tiny_app();
        let mut out: Vec<u8> = vec![];
        clap_complete::generate(shell, &mut app, "mapbox", &mut out);
        String::from_utf8(out).expect("a completion script is UTF-8")
    }

    #[test]
    fn every_named_shell_generates_something_naming_the_binary() {
        for (name, _) in SHELLS {
            let shell = shell_named(name).expect("a name in SHELLS resolves");
            let script = generate(shell);
            assert!(
                script.contains("mapbox"),
                "the {name} script never names the binary"
            );
            assert!(
                script.contains("get-style"),
                "the {name} script does not complete a subcommand of the tree it was built \
                 from: {script}"
            );
        }
    }

    /// The positional is what decides which generator runs, so clap's
    /// accepted set and `SHELLS` have to be the same set. They are built from
    /// one list today; this fails the day someone adds a spelling to the
    /// parser by hand.
    #[test]
    fn clap_accepts_exactly_the_shells_this_module_can_generate() {
        let cmd = command();
        let arg = cmd
            .get_arguments()
            .find(|arg| arg.get_id() == SHELL_ARG)
            .expect("the shell positional");
        let accepted: Vec<String> = arg
            .get_possible_values()
            .iter()
            .map(|value| value.get_name().to_string())
            .collect();

        assert_eq!(accepted, shell_names(), "clap's list drifted from SHELLS");
        for name in &accepted {
            assert!(
                shell_named(name).is_some(),
                "clap accepts `{name}` and nothing in SHELLS generates it — \
                 `run` would panic on it"
            );
        }
    }

    /// `run`'s `unwrap_or_else` panic is unreachable only while every name
    /// clap accepts resolves. Nothing else in the tree may take that
    /// positional's place, either — a second value would be parsed into the
    /// same id.
    #[test]
    fn the_shell_positional_is_required_and_takes_one_value() {
        let err = command()
            .try_get_matches_from(["completion"])
            .expect_err("a missing shell is a usage error");
        assert_eq!(err.kind(), clap::error::ErrorKind::MissingRequiredArgument);

        // Reported as an unknown argument rather than as too many values:
        // there is no second positional for the word to land in, which is the
        // shape that matters — `run` reads one id and would silently ignore
        // anything else.
        let err = command()
            .try_get_matches_from(["completion", "bash", "zsh"])
            .expect_err("two shells at once is a usage error");
        assert_eq!(err.kind(), clap::error::ErrorKind::UnknownArgument);
    }

    #[test]
    fn an_unknown_shell_is_refused_locally() {
        let err = command()
            .try_get_matches_from(["completion", "nushell"])
            .expect_err("a shell this CLI does not generate for is a usage error");
        assert_eq!(err.kind(), clap::error::ErrorKind::InvalidValue);
    }
}
