//! `mapbox generate-skills`: this CLI's own command surface, written out as
//! an Agent Skill.
//!
//! An agent handed a CLI it has never seen either runs `--help` sixty times
//! or guesses. `--schema` fixed the second half of that — the facts are
//! available as data — but an agent still has to know the command exists
//! before it can ask, and a schema says nothing about the parts that are true
//! of every command: where the token comes from, which stream the result
//! arrives on, what an error looks like.
//!
//! So this writes both halves down, once, into the directory the agent
//! already reads: a `SKILL.md` index with the cross-cutting rules, and one
//! reference page per service listing every command with its arguments, its
//! request and a worked example.
//!
//! # Where the content comes from
//!
//! [`crate::schema::build`] — the same walk `--schema` publishes, over the
//! same built [`Command`] tree, filtered by the same
//! [`crate::spec::Operation::is_exposed`]. Nothing here re-reads the OpenAPI
//! specs, and nothing here decides what is a command.
//!
//! That is the whole design. A second walk of the specs would be a second
//! opinion about what this CLI does, and the two would drift on the first
//! sync — advertising an operation the CLI withholds, which sends an agent to
//! a command that answers exactly as a typo does. Rendering the schema
//! instead makes three of the four guarantees the issue asks for structural
//! rather than tested: a withheld, disabled or liveness operation is absent
//! because it was never in the schema, and a command that exists is present
//! because `every_command_in_the_tree_is_described` fails the build
//! otherwise. The tests below still assert all four, because a guarantee
//! nothing checks is a comment.
//!
//! # Determinism
//!
//! Two runs against one build produce byte-identical trees, so a generated
//! skill can be committed and a diff means something changed. That rules out
//! timestamps, hostnames, absolute paths and hash-map iteration order: every
//! collection here is sorted explicitly, and line endings are written as `\n`
//! rather than the platform's.
//!
//! # Writing
//!
//! The skill directory is replaced, not merged — it is generated output, and
//! a half-updated one is worse than either version. So it is built in a
//! hidden sibling directory and renamed into place, and a directory holding
//! anything this command did not write is refused rather than overwritten.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use clap::{Arg, ArgAction, ArgMatches, Command};
use serde_json::json;
use sha2::{Digest, Sha256};

use crate::executor;
use crate::output::{self, CliError, Mode};
use crate::schema::{self, ArgKind, Argument, CommandEntry, Kind, Schema};
use crate::skill_dest::{self, AgentHomes, Destination};
use crate::spec::ServiceSpec;
use crate::tilesets_cli;

/// Subcommand users type: `mapbox generate-skills`.
pub const COMMAND: &str = "generate-skills";

/// The directory written under each destination, and the skill's `name` in
/// its own frontmatter — the two have to match for an agent to load it.
const SKILL_NAME: &str = "mapbox-cli";

/// The sentence that says a file is ours.
///
/// Kept short and kept whole: it is matched as a literal in the first
/// kibibyte of every file under the skill directory, and that match is the
/// only thing standing between a regenerate and someone else's work. See
/// [`strangers`].
const GENERATED_MARKER: &str = "Generated by `mapbox generate-skills`";

/// How far into a file the marker has to appear. Long enough for YAML
/// frontmatter and a heading to precede it, short enough that a stray
/// occurrence deep inside a hand-written document is not mistaken for one.
const MARKER_WINDOW: usize = 1024;

const SERVICE_ARG: &str = "service";
const FORCE_ARG: &str = "force";

/// Built beside the destination and renamed in, so a crash cannot leave a
/// half-written skill where an agent will read it.
const STAGING_DIR: &str = ".mapbox-cli.generating";

/// Where the directory being replaced waits until the new one is in place.
const ARCHIVE_DIR: &str = ".mapbox-cli.replaced";

const DRY_RUN_HELP: &str = "List the files this would write, then exit without writing them";

pub fn command() -> Command {
    Command::new(COMMAND)
        .about("Write Agent Skills describing this CLI's own commands, for a coding agent to read")
        .long_about(format!(
            "Write Agent Skills describing this CLI's own commands.\n\n\
             Produces a `{SKILL_NAME}` skill directory — a SKILL.md index, an \
             AGENTS.md carrying the same prose, and one reference page per command group \
             listing every command with its arguments, the request it makes and a \
             worked example.\n\n\
             The content is derived from the command tree this binary built, not from \
             the API specs, so it describes exactly the commands that exist: an \
             operation this CLI withholds, disables or treats as a liveness probe is \
             absent from the skill for the same reason it is absent from `--help`.\n\n\
             Two runs of one binary write byte-identical files, so the result can be \
             committed and a diff means the CLI changed. Nothing here reaches the \
             network, and no token is needed.\n\n\
             With no flags, writes into the project directory of every agent whose \
             home directory is present."
        ))
        .args(skill_dest::args())
        .arg(
            Arg::new(SERVICE_ARG)
                .long(SERVICE_ARG)
                .value_name("SERVICE")
                .action(ArgAction::Append)
                .help("Describe only this command group, repeatable. Defaults to all of them"),
        )
        .arg(
            Arg::new(FORCE_ARG)
                .long(FORCE_ARG)
                .action(ArgAction::SetTrue)
                .help("Replace a skill directory holding files this command did not write"),
        )
        .arg(executor::dry_run_arg(DRY_RUN_HELP))
}

pub fn run(app: &Command, specs: &[ServiceSpec], matches: &ArgMatches, mode: Mode) -> Result<()> {
    let schema = schema::build(app, specs, &[]);
    let header = Header::new(requested_services(&schema, matches)?);
    let files = render(app, &schema, &header);

    let homes = AgentHomes::from_env();
    let destinations = skill_dest::from_matches(matches, &homes, true)?;
    let force = matches.get_flag(FORCE_ARG);

    // Every destination is checked before any of them is written: a refusal
    // on the second one, after the first has been replaced, leaves the caller
    // having to work out which half happened.
    let plans: Vec<Plan> = destinations
        .into_iter()
        .map(|destination| plan(destination, files.clone(), force))
        .collect::<Result<_>>()?;

    let dry_run = executor::wants_dry_run(matches);
    if !dry_run {
        for plan in &plans {
            apply(plan)?;
        }
    }

    report(mode, &plans, dry_run)
}

/// The services to describe, or `None` for all of them.
///
/// An unrecognised name is an error naming the alternatives rather than a
/// silent no-op: `--service style` is a typo, and writing a skill that
/// describes nothing is a worse answer to it than refusing.
fn requested_services(schema: &Schema, matches: &ArgMatches) -> Result<Option<Vec<String>>> {
    let requested: Vec<&String> = matches
        .get_many::<String>(SERVICE_ARG)
        .into_iter()
        .flatten()
        .collect();
    if requested.is_empty() {
        return Ok(None);
    }

    let known: BTreeSet<&str> = schema
        .commands
        .iter()
        .map(|entry| entry.service.as_str())
        .collect();

    let mut wanted: Vec<String> = vec![];
    for name in requested {
        if !known.contains(name.as_str()) {
            return Err(CliError::new(
                "unknown_service",
                format!(
                    "`{name}` is not a command group of this CLI. Pick from: {}.",
                    known.iter().copied().collect::<Vec<&str>>().join(", ")
                ),
            )
            .into());
        }
        if !wanted.iter().any(|seen| seen == name) {
            wanted.push(name.clone());
        }
    }
    wanted.sort();
    Ok(Some(wanted))
}

/// What every generated file says about the build that wrote it.
///
/// Three facts, and deliberately only three: the CLI version, which fixes the
/// hand-written commands and the output contract; the spec digest, which
/// fixes the generated ones; and the openapi-specs commit, when the build
/// could work one out. A reader comparing the digest against a fresh
/// `mapbox generate-skills --dry-run` learns whether the skill is stale,
/// which is the only question a header can usefully answer.
///
/// No timestamp, no hostname, no path. Each would make two runs of one binary
/// differ, which is the property that lets a generated skill be committed.
struct Header {
    cli_version: &'static str,
    spec_digest: String,
    /// From `build.rs`, which reads the commit `openapi/` was derived from
    /// out of a maintainer-only manifest file. Absent
    /// whenever that file is missing or malformed, which is why the digest
    /// above is the primary signal and this is the convenience. Says nothing
    /// about a `custom-openapi/` spec, which the digest also covers — including
    /// `custom-openapi/statistics/`, folded in by hand in `spec_digest()`
    /// since it's `include_str!`'d directly by `account_usage.rs` rather
    /// than reachable through `CUSTOM_SPEC_ENTRIES`.
    spec_commit: Option<&'static str>,
    /// Set only when `--service` narrowed the skill, since a reader otherwise
    /// has no way to tell a partial skill from a complete one.
    services: Option<Vec<String>>,
}

impl Header {
    fn new(services: Option<Vec<String>>) -> Self {
        Header {
            cli_version: env!("CARGO_PKG_VERSION"),
            spec_digest: spec_digest(),
            spec_commit: option_env!("MAPBOX_SPEC_COMMIT").map(str::trim),
            services,
        }
    }

    fn comment(&self) -> String {
        let specs = match self.spec_commit {
            Some(commit) if !commit.is_empty() => {
                format!(
                    "openapi-specs {commit}, content digest {} (also covers custom-openapi)",
                    self.spec_digest
                )
            }
            _ => format!(
                "content digest {} (openapi-specs + custom-openapi)",
                self.spec_digest
            ),
        };

        let mut lines = vec![
            format!("<!-- {GENERATED_MARKER} — do not edit; regenerate instead."),
            format!("     {SKILL_NAME} {}", self.cli_version),
            format!("     {specs}"),
        ];
        if let Some(services) = &self.services {
            lines.push(format!("     command groups: {}", services.join(", ")));
        }
        lines.push("-->".to_string());
        lines.join("\n")
    }

    /// Whether the requested services include this one. Everything is
    /// included when `--service` said nothing.
    fn includes(&self, service: &str) -> bool {
        self.services
            .as_ref()
            .is_none_or(|wanted| wanted.iter().any(|name| name == service))
    }
}

/// Whether a file's first kibibyte claims this command wrote it.
fn marker_in(contents: &[u8]) -> bool {
    let head = &contents[..contents.len().min(MARKER_WINDOW)];
    head.windows(GENERATED_MARKER.len())
        .any(|window| window == GENERATED_MARKER.as_bytes())
}

/// A short digest of the OpenAPI content this binary was compiled against.
///
/// The specs are embedded by `include_str!`, so this is the content of the
/// build rather than of the working tree — which is the honest thing for a
/// generated document to record, and the reason it is preferred over the git
/// commit above. Sorted by service name and separated by NUL, so the digest
/// depends on the specs and not on the order they happen to be declared in,
/// and so no rename can produce the same bytes as some other pairing.
fn spec_digest() -> String {
    // The effective list, so a hand-authored spec under `custom-openapi/`
    // moves the digest the same way an openapi-specs change does. Plus
    // `statistics`, `include_str!`'d directly by `account_usage.rs` rather
    // than reachable through `effective_spec_entries()` — without this line
    // added by hand, editing that one spec would leave every generated
    // skill's digest unchanged.
    let compiled_in = crate::spec::effective_spec_entries();
    let mut entries: Vec<(&str, &str)> = compiled_in
        .iter()
        .map(|entry| (entry.name, entry.yaml))
        .chain(std::iter::once(("statistics", crate::account_usage::SPEC)))
        .collect();
    entries.sort_unstable_by_key(|(name, _)| *name);

    let mut hasher = Sha256::new();
    for (name, yaml) in entries {
        hasher.update(name.as_bytes());
        hasher.update([0]);
        hasher.update(yaml.as_bytes());
        hasher.update([0]);
    }

    hasher
        .finalize()
        .iter()
        .take(6)
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

/// One file, and where it goes relative to the skill directory.
#[derive(Clone, Debug, PartialEq, Eq)]
struct GeneratedFile {
    path: PathBuf,
    contents: String,
}

/// One destination's worth of work, decided but not yet done.
#[derive(Debug)]
struct Plan {
    destination: Destination,
    files: Vec<GeneratedFile>,
}

impl Plan {
    /// The directory the files go in — the destination's skills root plus the
    /// skill's own name.
    fn skill_dir(&self) -> PathBuf {
        self.destination.root.join(SKILL_NAME)
    }
}

/// Every service that has commands to describe, sorted, each with its
/// commands sorted.
///
/// A `BTreeMap` rather than a `HashMap` because the order is output: two runs
/// of one binary have to write the same bytes, and hash iteration order is
/// not a promise.
fn by_service<'a>(schema: &'a Schema, header: &Header) -> BTreeMap<&'a str, Vec<&'a CommandEntry>> {
    let mut out: BTreeMap<&str, Vec<&CommandEntry>> = BTreeMap::new();
    for entry in &schema.commands {
        if header.includes(&entry.service) {
            out.entry(entry.service.as_str()).or_default().push(entry);
        }
    }
    for entries in out.values_mut() {
        entries.sort_by(|a, b| a.name.cmp(&b.name));
    }
    out
}

fn render(app: &Command, schema: &Schema, header: &Header) -> Vec<GeneratedFile> {
    let grouped = by_service(schema, header);
    let body = render_body(app, schema, &grouped, header);

    let mut files = vec![
        GeneratedFile {
            path: PathBuf::from("SKILL.md"),
            contents: render_skill_md(&body, header),
        },
        GeneratedFile {
            path: PathBuf::from("AGENTS.md"),
            contents: render_agents_md(&body, header),
        },
    ];

    for (service, entries) in &grouped {
        let (title, description) = service_about(app, service);
        files.push(GeneratedFile {
            path: PathBuf::from("references").join(format!("{service}.md")),
            contents: render_service_reference(
                service,
                &title,
                description.as_deref(),
                entries,
                header,
            ),
        });
    }

    files
}

/// SKILL.md: frontmatter first, because the Agent Skills format requires the
/// `---` fence to be the very first bytes of the file, then the generated
/// header, then the shared prose.
fn render_skill_md(body: &str, header: &Header) -> String {
    let description = "Use the mapbox CLI to call Mapbox APIs — styles, tiles, static images, \
                       geocoding, tilesets, fonts and access tokens — and to authenticate, \
                       preview requests and read its output.";
    format!(
        "---\nname: {SKILL_NAME}\ndescription: \"{description}\"\n---\n\n{}\n\n{body}",
        header.comment()
    )
}

/// AGENTS.md: the same prose under a heading, for an agent that reads
/// `AGENTS.md` and knows nothing about skills.
///
/// The body is byte-identical to SKILL.md's — pinned by
/// `the_agents_md_and_skill_md_bodies_are_identical`, because two documents
/// that are supposed to say the same thing and are written twice say two
/// things within a month. Only the wrapper differs: the frontmatter is a
/// skill-loader's business, and the heading is what a plain Markdown reader
/// needs in its place.
fn render_agents_md(body: &str, header: &Header) -> String {
    format!("# mapbox CLI\n\n{}\n\n{body}", header.comment())
}

/// A service's summary and its longer description, off the built tree.
///
/// Read from clap rather than from the `ServiceSpec` so the four
/// hand-written groups — `auth`, `tilesets-cli`, `generate-skills` — are
/// described the same way the generated ones are, and so a service whose
/// about line is reworded in `build_app` is reworded here too.
fn service_about(app: &Command, service: &str) -> (String, Option<String>) {
    match app.find_subcommand(service) {
        Some(cmd) => (
            cmd.get_about().map(ToString::to_string).unwrap_or_default(),
            cmd.get_long_about().map(ToString::to_string),
        ),
        None => (String::new(), None),
    }
}

fn render_body(
    app: &Command,
    schema: &Schema,
    grouped: &BTreeMap<&str, Vec<&CommandEntry>>,
    header: &Header,
) -> String {
    let mut out = String::new();

    out.push_str(
        "## When to use this\n\n\
         Reach for `mapbox` whenever a task involves a Mapbox API: reading or writing \
         styles, fetching tiles or static images, geocoding, querying tilesets, \
         listing or inspecting access tokens. It is one binary, it needs no SDK, and \
         every command answers on stdout in a shape a program can read.\n\n\
         Do not hand-write a `curl` against `api.mapbox.com` when a command exists — \
         the command already knows the URL, the required parameters, the token and the \
         error shape. `mapbox --schema <command>` prints all of that as JSON if you \
         need to check before running.\n\n",
    );

    out.push_str("## The one-minute version\n\n```sh\n");
    for line in [
        "mapbox auth whoami",
        "mapbox styles list -u USERNAME",
        "mapbox --schema styles list",
    ] {
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(
        "```\n\n\
         The first says which token the next command will use and whose it is. The \
         second runs a real request. The third describes a command without running \
         it, which is the cheapest way to learn what one takes.\n\n",
    );

    out.push_str("## Authentication\n\n");
    out.push_str(
        "Every command that makes a request needs an access token. The CLI sends it as \
         the `access_token` query parameter, so it is never one of the arguments listed \
         in a reference page. It is resolved from these, highest first:\n\n",
    );
    for (index, (_, prose)) in token_precedence().iter().enumerate() {
        out.push_str(&format!("{}. {prose}\n", index + 1));
    }
    out.push_str(
        "\nThe account a URL asks for is separate from the token: pass `--username`/`-u`, \
         set `MAPBOX_USERNAME`, or let a stored login supply it. A command whose URL has \
         an account placeholder cannot run without one.\n\n\
         `--use-login` removes step 2, and only step 2 — a `--token` typed on the command \
         line still wins. It is the flag to reach for when a token left in a shell profile \
         is shadowing a login for a different account.\n\n",
    );

    out.push_str("## The output contract\n\n");
    out.push_str(&format!(
        "stdout carries the result and nothing else. Warnings, progress and errors go to \
         stderr, so a pipe reads clean.\n\n\
         `--output`/`-o` takes `{auto}`, `{text}` or `{json}`, and defaults to `{auto}`: \
         text at a terminal, JSON when stdout is a pipe or a file. So a script gets JSON \
         without asking, and a person gets a table without asking. `{env}` sets the same \
         thing for a session.\n\n\
         Three things are exempt, and each for a reason worth knowing:\n\n\
         - A binary response — a tile, a static image, a font glyph range — is written to \
         stdout as bytes whatever `--output` says. Redirect it to a file.\n\
         - `--help` and `--version` are clap's own rendering, not a result.\n\
         - `mapbox {tilesets_cli}` forwards to another program, which has no equivalent option; \
         `--output` written before it earns a warning on stderr and changes nothing.\n\n\
         `--id <ID>` picks one row out of a command that returns a list, in either mode.\n\n",
        auto = output::AUTO,
        text = output::TEXT,
        json = output::JSON,
        env = output::ENV,
        tilesets_cli = tilesets_cli::COMMAND,
    ));

    out.push_str("## Errors\n\n");
    out.push_str(
        "A failure exits non-zero and writes to stderr. Under `json` it is one object with \
         a machine-readable `code`, a `message`, and `status` when the failure came from an \
         HTTP response — so a caller can branch on the code rather than parsing prose. \
         Under `text` it is the message, plus a tip where there is one to give.\n\n\
         Two codes are worth special-casing: `missing_subcommand` means the command line \
         named a command group but no operation, and an HTTP `401` means the token is the \
         problem — the message says which of the sources above supplied it.\n\n",
    );

    out.push_str("## Dry runs\n\n");
    out.push_str(&format!(
        "Every command that changes something takes `--{dry}`: it prints the request it \
         would send, or the file it would change, and exits without doing it. Commands \
         that only read do not have the flag, so its presence in a reference page's \
         argument table is itself the answer to whether a command mutates anything.\n\n\
         Use it before any destructive command you have not run before. It costs nothing \
         and it is the only way to see the resolved URL without spending the request.\n\n",
        dry = executor::DRY_RUN_ARG,
    ));

    out.push_str("## Describing a command as JSON\n\n");
    out.push_str(&format!(
        "`mapbox --{schema_arg} <command>` prints the full description of a command as \
         JSON: every argument with its type, whether it is required, the values it \
         accepts, where it lands in the request, and the method and URL template. It \
         works at every level — `mapbox --{schema_arg}` for the whole CLI, \
         `mapbox --{schema_arg} styles` for one service, `mapbox --{schema_arg} styles \
         list` for one command — and needs no token, because it makes no request.\n\n\
         Prefer it over `--help` when a program is choosing the arguments. The reference \
         pages here shorten a description that will not fit a table cell; \
         `--{schema_arg}` has the whole of every one.\n\n",
        schema_arg = schema::ARG,
    ));

    out.push_str(&format!(
        "## `mapbox {}` is a proxy\n\n",
        tilesets_cli::COMMAND
    ));
    out.push_str(&format!(
        "`mapbox {cmd}` forwards everything after the subcommand name, verbatim, to the \
         separately-installed `{binary}` binary from the Python package `mapbox-tilesets`. \
         Two consequences that catch everyone:\n\n\
         - A `mapbox` global written *after* `{cmd}` goes to the child, which has never \
         heard of it. Write globals before the subcommand name: \
         `mapbox --{schema_arg} {cmd}`, not `mapbox {cmd} --{schema_arg}`.\n\
         - `mapbox {cmd} --help` shows the child's help, not this CLI's.\n\n\
         Its token is resolved as above and passed in the child's environment rather than \
         its argv, so it never appears in `ps`. A `--token` written after `{cmd}` is \
         forwarded and wins, which is the documented way to use a different token for one \
         call. `--use-login` is the mirror image: it makes a stored login outrank a token \
         already exported in the shell — worth knowing, because the Tilesets API answers a \
         wrong-account token with a bare `Not found` that points nowhere near the cause.\n\n",
        cmd = tilesets_cli::COMMAND,
        binary = tilesets_cli::DEFAULT_BINARY,
        schema_arg = schema::ARG,
    ));

    out.push_str("## Command groups\n\n");
    out.push_str("| Command group | Commands | What it covers | Reference |\n|---|---|---|---|\n");
    for (service, entries) in grouped {
        let (title, _) = service_about(app, service);
        out.push_str(&format!(
            "| `{service}` | {} | {} | [references/{service}.md](references/{service}.md) |\n",
            entries.len(),
            cell(crate::first_sentence(&title)),
        ));
    }
    out.push('\n');

    out.push_str("## Global options\n\n");
    out.push_str(
        "Accepted by every command, in any position — except after \
         `mapbox tilesets-cli`, per the section above.\n\n",
    );
    out.push_str("| Option | Type | Values | Default | Environment | Description |\n|---|---|---|---|---|---|\n");
    let mut globals: Vec<&Argument> = schema.global_options.iter().collect();
    globals.sort_by_key(|arg| spelling(arg));
    for arg in globals {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            written_cell(arg),
            arg.value_type,
            values_cell(arg),
            arg.default.as_deref().map(code).unwrap_or_default(),
            arg.env.as_deref().map(code).unwrap_or_default(),
            describe(arg),
        ));
    }
    out.push('\n');

    out.push_str(&format!(
        "---\n\nThis skill was generated from the command tree of `{SKILL_NAME}` \
         {}. Regenerate it with `mapbox generate-skills` after upgrading the CLI; \
         do not edit it by hand.\n",
        header.cli_version,
    ));

    out
}

/// One service's commands, in full.
fn render_service_reference(
    service: &str,
    title: &str,
    description: Option<&str>,
    entries: &[&CommandEntry],
    header: &Header,
) -> String {
    let mut out = format!("{}\n\n# mapbox {service}\n\n", header.comment());

    // A hand-written leaf is its own service — `generate-skills`, the proxy —
    // so the page heading, the service's about line and the one command's
    // summary are three copies of one sentence. The command's own block has
    // to stay, because that is the `###` heading every command is found by,
    // so the service-level intro is what gives way.
    let echoes = entries.len() == 1
        && entries[0].name == service
        && entries[0].summary.trim() == title.trim();

    if !echoes {
        if !title.is_empty() {
            out.push_str(&format!("{}\n\n", demote_headings(title)));
        }
        if let Some(description) = description.filter(|text| !text.trim().is_empty()) {
            out.push_str(&format!("{}\n\n", demote_headings(description.trim())));
        }
    }

    out.push_str(&format!(
        "{} command{}. A description too long for its table cell is shortened here; \
         `mapbox --{schema_arg} <command>` has the whole of every one, as JSON. \
         Placeholders in the examples are written in `UPPER_CASE` and have to be \
         replaced.\n\n## Commands\n\n",
        entries.len(),
        if entries.len() == 1 { "" } else { "s" },
        schema_arg = schema::ARG,
    ));

    for entry in entries {
        out.push_str(&format!("### {}\n\n", entry.command));

        if !entry.summary.trim().is_empty() {
            out.push_str(&format!("{}\n\n", demote_headings(entry.summary.trim())));
        }
        if let Some(description) = entry
            .description
            .as_deref()
            .filter(|text| !text.trim().is_empty())
        {
            out.push_str(&format!("{}\n\n", demote_headings(description.trim())));
        }

        if let Some(request) = &entry.request {
            out.push_str(&format!("`{} {}`\n\n", request.method, request.url));
        }
        if let Some(forwards_to) = entry.forwards_to {
            out.push_str(&format!("Forwards to the `{forwards_to}` binary.\n\n"));
        }
        if let Some(note) = entry.note {
            out.push_str(&format!("{note}\n\n"));
        }

        out.push_str(&arguments_table(entry));

        if let Some(detail) = &entry.detail_command {
            out.push_str(&format!(
                "To fetch one of the things this returns, see `{detail}`.\n\n"
            ));
        }

        out.push_str(&format!("```sh\n{}\n```\n\n", example_line(entry)));
    }

    out
}

/// An entry's arguments, in the order a caller writes them.
///
/// Positionals keep clap's declared order, because that order *is* how they
/// are identified — sorting them would describe a different command. Flags
/// have no order, so they are sorted by their long spelling: a table whose
/// rows move when an unrelated parameter is added is a table nobody can diff.
fn ordered_arguments(entry: &CommandEntry) -> Vec<&Argument> {
    let mut out: Vec<&Argument> = entry
        .arguments
        .iter()
        .filter(|arg| arg.kind == ArgKind::Positional)
        .collect();

    let mut flags: Vec<&Argument> = entry
        .arguments
        .iter()
        .filter(|arg| arg.kind != ArgKind::Positional)
        .collect();
    flags.sort_by_key(|arg| spelling(arg));

    out.extend(flags);
    out
}

fn arguments_table(entry: &CommandEntry) -> String {
    let arguments = ordered_arguments(entry);
    if arguments.is_empty() {
        return "Takes no arguments of its own.\n\n".to_string();
    }

    let mut out = String::from(
        "| Argument | Written as | Required | Type | Values | Description |\n\
         |---|---|---|---|---|---|\n",
    );
    for arg in arguments {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            arg.name,
            written_cell(arg),
            required_cell(arg),
            arg.value_type,
            values_cell(arg),
            describe(arg),
        ));
    }
    out.push('\n');
    out
}

/// The long flag, or the name for a positional. The sort key for anything
/// that has no inherent order.
fn spelling(arg: &Argument) -> String {
    arg.flag.clone().unwrap_or_else(|| arg.name.clone())
}

/// How the argument is typed on the command line, with its value shown as
/// something to replace.
fn written_as(arg: &Argument) -> String {
    match arg.kind {
        ArgKind::Positional => value_name(arg),
        ArgKind::Flag => spelling(arg),
        ArgKind::Option => format!("{} {}", spelling(arg), value_name(arg)),
    }
}

/// The same, as a table cell: the short spelling beside the long one, and a
/// note where the argument is one the command does not declare.
///
/// The short matters more than it looks. `-u` is how everyone writes
/// `--username`, and an agent that has only ever seen the long form will
/// read `-u` in someone's script as an unknown flag.
fn written_cell(arg: &Argument) -> String {
    let mut parts = vec![code(&written_as(arg))];
    if let Some(short) = &arg.short {
        parts.push(code(short));
    }
    if arg.source == Some("global") {
        parts.push("(global)".to_string());
    }
    parts.join(" ")
}

/// A value's name in a table: the argument's own, in the shape a reader
/// replaces.
///
/// Never a real accepted value. `--output auto` in a "written as" cell reads
/// as advice about what to pass rather than as a placeholder, and the Values
/// column already says which values there are. The examples are the other
/// way round — see [`placeholder`], which has to produce something the
/// parser accepts.
fn value_name(arg: &Argument) -> String {
    if arg.value_type == "path" {
        return "PATH".to_string();
    }
    // `uploadId` reads better as `UPLOAD_ID` than as `UPLOADID`, and the
    // specs spell parameters both ways.
    let mut out = String::new();
    let mut previous: Option<char> = None;
    for ch in arg.name.chars() {
        if ch.is_ascii_uppercase()
            && previous.is_some_and(|p| p.is_ascii_lowercase() || p.is_ascii_digit())
        {
            out.push('_');
        }
        out.push(if ch == '-' { '_' } else { ch });
        previous = Some(ch);
    }
    out.to_uppercase()
}

fn required_cell(arg: &Argument) -> String {
    if !arg.required_one_of.is_empty() {
        let flags: Vec<String> = arg
            .required_one_of
            .iter()
            .map(|name| format!("`--{name}`"))
            .collect();
        return format!("one of {}", flags.join(" / "));
    }
    if arg.required {
        "yes".to_string()
    } else {
        "no".to_string()
    }
}

/// At most a handful of accepted values, with a count for the rest.
///
/// Some spec enums run to dozens of languages or place types. Printing all of
/// them turns a reference page into a word list, and truncating without
/// saying so would make the table look like the whole truth — hence the
/// count and the pointer to `--schema`, which does publish all of them.
fn values_cell(arg: &Argument) -> String {
    const SHOWN: usize = 6;
    if arg.values.is_empty() {
        return String::new();
    }

    let shown: Vec<String> = arg
        .values
        .iter()
        .take(SHOWN)
        .map(|value| {
            if value.is_empty() {
                "`\"\"`".to_string()
            } else {
                code(value)
            }
        })
        .collect();

    let mut out = shown.join(", ");
    if arg.values.len() > SHOWN {
        out.push_str(&format!(" (+{} more)", arg.values.len() - SHOWN));
    }
    out
}

/// How much description one table cell will carry.
const CELL_BUDGET: usize = 220;

/// A description fit for a table cell, cut only where there is something to
/// cut.
///
/// Spec descriptions are paragraphs — `geocoder --types` alone is 4.6 KB —
/// and those are shortened to their first sentence, with `--schema` holding
/// the rest. A clap help string is not: it is already one line, written to
/// fit, and `crate::first_sentence` would cut `--output`'s at the `.` in
/// "Output format." and throw away everything that says what the formats
/// are. So the cut applies by length, to the text that would overflow.
fn summarise(text: &str) -> String {
    let whole = cell(text);
    if whole.len() <= CELL_BUDGET {
        return whole;
    }
    cell(crate::first_sentence(text))
}

/// The description, plus the handful of facts that would otherwise need a
/// column of their own.
///
/// Returns text that is already safe for a table cell, so a caller must not
/// escape it again — `cell` is not idempotent.
fn describe(arg: &Argument) -> String {
    let mut parts: Vec<String> = vec![];

    if let Some(description) = arg.description.as_deref() {
        let summary = summarise(description);
        if !summary.is_empty() {
            let ends_a_sentence = summary.ends_with('.') || summary.ends_with('!');
            parts.push(if ends_a_sentence {
                summary
            } else {
                format!("{summary}.")
            });
        }
    }
    if let Some(location) = arg.location {
        parts.push(format!("Sent in the request {location}."));
    }
    if let Some(content_type) = &arg.content_type {
        parts.push(format!("Sent as `{content_type}`."));
    }
    if let Some(field) = &arg.multipart_field {
        // `--file`'s own help already names the field on the multipart
        // operations, and saying it twice reads as a stutter.
        if !parts
            .iter()
            .any(|part| part.contains(&format!("`{field}`")))
        {
            parts.push(format!("Multipart field `{field}`."));
        }
    }
    // Several help strings already end with "repeatable", and "repeatable.
    // Repeatable." reads as a stutter rather than as emphasis.
    if arg.repeatable
        && !parts
            .iter()
            .any(|part| part.to_lowercase().contains("repeatable"))
    {
        parts.push("Repeatable.".to_string());
    }
    if arg.omit_with_empty {
        parts.push("Pass an empty string to leave it out of the URL.".to_string());
    }
    if !arg.conflicts_with.is_empty() {
        let others: Vec<String> = arg
            .conflicts_with
            .iter()
            .map(|name| format!("`--{name}`"))
            .collect();
        parts.push(format!("Cannot be given with {}.", others.join(" or ")));
    }
    if let Some(fills) = &arg.fills {
        parts.push(format!("Fills `{fills}` in the URL."));
    }

    parts.join(" ")
}

/// A ready-to-run invocation of one command: every argument it cannot do
/// without, and nothing it can.
///
/// Parseability is the hard requirement — `every_generated_example_parses`
/// hands each of these back to the very command tree it came from — so the
/// values respect each argument's declared enum and numeric type. Realism is
/// the soft one: where the argument accepts anything, the placeholder is its
/// own name in upper case, which reads as something to replace and cannot be
/// mistaken for a working value.
fn example_line(entry: &CommandEntry) -> String {
    // The proxy's own argument soaks up the child's whole command line, so
    // there is no argument here worth filling in. `--help` is both the
    // honest example and the first thing anyone should run.
    if entry.kind == Kind::Passthrough {
        return format!("{} --help", entry.command);
    }

    let mut words = vec![entry.command.clone()];

    // The globals a request cannot be built without go first, where a reader
    // is used to seeing them, and where they are visibly not part of the
    // command's own arguments.
    for arg in ordered_arguments(&entry_globals(entry)) {
        words.push(format!(
            "{} {}",
            spelling(arg),
            shell_word(&placeholder(arg))
        ));
    }

    let alternative = entry
        .arguments
        .iter()
        .filter_map(|arg| arg.required_one_of.first())
        .next()
        .cloned();

    for arg in ordered_arguments(entry) {
        if arg.source.is_some() {
            continue;
        }
        let needed = arg.required || Some(&arg.name) == alternative.as_ref();
        if !needed {
            continue;
        }
        match arg.kind {
            ArgKind::Positional => words.push(shell_word(&placeholder(arg))),
            ArgKind::Flag => words.push(spelling(arg)),
            ArgKind::Option => {
                words.push(spelling(arg));
                words.push(shell_word(&placeholder(arg)));
            }
        }
    }

    words.join(" ")
}

/// The entry's global arguments, wrapped so `ordered_arguments` can sort them
/// the same way it sorts everything else.
///
/// A borrow rather than a clone would need a second sorting helper for a
/// two-element list; this is the cheaper of the two.
fn entry_globals(entry: &CommandEntry) -> CommandEntry {
    CommandEntry {
        command: entry.command.clone(),
        service: entry.service.clone(),
        name: entry.name.clone(),
        kind: entry.kind,
        summary: String::new(),
        description: None,
        // Irrelevant here: this copy exists only to reuse the arguments'
        // sort, and nothing reads deprecation off it.
        deprecated: false,
        request: None,
        detail_command: None,
        forwards_to: None,
        note: None,
        aliases: vec![],
        arguments: entry
            .arguments
            .iter()
            .filter(|arg| arg.source == Some("global") && arg.required)
            .map(clone_argument)
            .collect(),
    }
}

fn clone_argument(arg: &Argument) -> Argument {
    Argument {
        name: arg.name.clone(),
        kind: arg.kind,
        flag: arg.flag.clone(),
        short: arg.short.clone(),
        required: arg.required,
        value_type: arg.value_type,
        values: arg.values.clone(),
        description: arg.description.clone(),
        repeatable: arg.repeatable,
        location: arg.location,
        source: arg.source,
        content_type: arg.content_type.clone(),
        multipart_field: arg.multipart_field.clone(),
        conflicts_with: arg.conflicts_with.clone(),
        required_one_of: arg.required_one_of.clone(),
        fills: arg.fills.clone(),
        omit_with_empty: arg.omit_with_empty,
        env: arg.env.clone(),
        default: arg.default.clone(),
    }
}

/// A value the argument will accept.
fn placeholder(arg: &Argument) -> String {
    // A declared enum leaves no choice: anything else is rejected by the
    // parser, so an example using a name placeholder would not run. Values
    // holding a single quote are skipped because `split_example` has no
    // escaping to express them — no bundled spec has one, and the example
    // test fails loudly if that ever changes.
    if let Some(value) = arg
        .values
        .iter()
        .find(|value| !value.is_empty() && !value.contains('\''))
    {
        return value.clone();
    }

    match arg.value_type {
        // Small, valid, and true of every numeric parameter the specs
        // declare: zoom, tile coordinates, longitudes, latitudes, limits.
        "integer" | "number" => "0".to_string(),
        _ if arg
            .content_type
            .as_deref()
            .is_some_and(|ct| ct.contains("json")) =>
        {
            "{}".to_string()
        }
        _ => value_name(arg),
    }
}

/// A value as one shell word, quoting only where it has to.
///
/// Single quotes and nothing else, matching [`split_example`] exactly. The
/// pair is the whole of this module's shell handling, and keeping it this
/// small is what makes the round trip checkable.
fn shell_word(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }
    let plain = value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "._@/,:+=-".contains(c));
    if plain {
        value.to_string()
    } else {
        format!("'{value}'")
    }
}

/// A generated example split back into argv.
///
/// Understands single quotes and whitespace, and deliberately nothing else:
/// no double quotes, no backslash escapes, no variable expansion. That is
/// enough for everything [`shell_word`] can produce, and a parser that
/// handled more would be one that could disagree with the writer about a case
/// neither was tested on.
///
/// Only the tests read an example back — writing one is the command's job —
/// so this is compiled only for them.
#[cfg(test)]
fn split_example(line: &str) -> Vec<String> {
    let mut words = vec![];
    let mut current = String::new();
    let mut started = false;
    let mut quoted = false;

    for ch in line.chars() {
        match ch {
            '\'' => {
                quoted = !quoted;
                started = true;
            }
            c if c.is_whitespace() && !quoted => {
                if started {
                    words.push(std::mem::take(&mut current));
                    started = false;
                }
            }
            c => {
                current.push(c);
                started = true;
            }
        }
    }
    if started {
        words.push(current);
    }
    words
}

/// Spec prose, fitted underneath the heading it belongs to.
///
/// An OpenAPI `description` is Markdown, and the specs use it as such: the
/// geocoder's batch operation carries its own `### Example request` and
/// `### Response` headings, with a fenced `curl` block under each. Pasted
/// verbatim beneath a `###` command heading, those outrank the command they
/// describe — and one written at exactly `###` is indistinguishable from
/// another command's heading. That is not cosmetic: it is how
/// `every_command_appears_in_exactly_one_generated_file` reads the page, and
/// how an agent skimming for a command name reads it too.
///
/// So a heading in embedded prose is demoted to sit below the command's.
/// Lines inside a fenced block are left exactly as they are — a `#` there is
/// a shell comment or a colour, and rewriting one would corrupt the example
/// it belongs to.
fn demote_headings(text: &str) -> String {
    /// One level below the `###` a command heading uses.
    const UNDER: usize = 4;

    let mut out: Vec<String> = vec![];
    let mut fenced = false;

    for line in text.lines() {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            out.push(line.to_string());
            continue;
        }

        let hashes = line.chars().take_while(|c| *c == '#').count();
        let heading = !fenced && hashes > 0 && hashes < UNDER && line[hashes..].starts_with(' ');
        if heading {
            out.push(format!("{}{}", "#".repeat(UNDER), &line[hashes..]));
        } else {
            out.push(line.to_string());
        }
    }

    out.join("\n")
}

/// Text fit for a Markdown table cell: no newlines, and no `|` that would end
/// the cell early.
fn cell(text: &str) -> String {
    let collapsed: String = text
        .split_whitespace()
        .collect::<Vec<&str>>()
        .join(" ")
        .replace('|', "\\|");
    collapsed
}

/// A value as inline code, with its own `|` escaped for the table around it.
fn code(text: &str) -> String {
    format!("`{}`", text.replace('|', "\\|"))
}

/// The token sources, in the order the CLI applies them, each with the prose
/// the skill publishes for it.
///
/// Written as a table keyed by [`crate::auth::TokenSource`] rather than as
/// three sentences, so `the_documented_token_precedence_is_the_resolvers`
/// can compare it against the resolver itself. Documentation of a precedence
/// that is not the precedence is worse than none: an agent that believes it
/// would debug the wrong token for an hour.
fn token_precedence() -> [(crate::auth::TokenSource, &'static str); 3] {
    use crate::auth::TokenSource;
    [
        (
            TokenSource::Flag,
            "`--token`/`-t`, typed on the command line. Outranks everything, including \
             `--use-login`.",
        ),
        (
            TokenSource::Environment,
            "`MAPBOX_ACCESS_TOKEN` in the environment. The legacy spelling \
             `MapboxAccessToken` is read only by `mapbox tilesets-cli`, which forwards to a \
             tool that accepts it. `--use-login` skips this step.",
        ),
        (
            TokenSource::Login,
            "Credentials stored by `mapbox auth login`, refreshed automatically when \
             stale. `--profile <NAME>` picks which set.",
        ),
    ]
}

/// A path relative to a skill directory, rendered with `/` regardless of the
/// host OS.
///
/// `GeneratedFile::path` and `strangers()`'s output are logical positions
/// inside the generated tree (`references/styles.md`), not filesystem paths
/// to hand to `std::fs` — those still go through `Path`/`PathBuf` untouched.
/// `Path::display()` uses the platform separator, so without this a Windows
/// build would report `references\styles.md` in text output and JSON alike:
/// a value that varies with the host OS in output the byte-identical and
/// dry-run tests pin, and a JSON string an agent would need to special-case
/// per platform to parse back into the paths this same command just wrote.
fn slashed(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

/// Decides what one destination's write would be, and refuses one that would
/// destroy something.
///
/// The skill directory is ours to replace only if every file in it says so.
/// One stranger — a note someone left, a file a later version of another tool
/// dropped in — and the whole directory is off limits, because there is no
/// way to tell "a file we no longer generate" from "a file that matters"
/// without asking. Naming the offenders is what makes `--force` a decision
/// rather than a reflex.
fn plan(destination: Destination, files: Vec<GeneratedFile>, force: bool) -> Result<Plan> {
    let plan = Plan { destination, files };

    if !force {
        let root = plan.skill_dir();
        let strangers = strangers(&root)?;
        if !strangers.is_empty() {
            let listed: Vec<String> = strangers
                .iter()
                .map(|path| format!("  {}", slashed(path)))
                .collect();
            return Err(CliError::new(
                "not_generated",
                format!(
                    "{} holds {} file{} `mapbox {COMMAND}` did not write:\n{}\nMove them \
                     elsewhere, or pass --force to replace the whole directory.",
                    root.display(),
                    strangers.len(),
                    if strangers.len() == 1 { "" } else { "s" },
                    listed.join("\n"),
                ),
            )
            .into());
        }
    }

    Ok(plan)
}

/// Every file under `root` that does not carry the generated marker, relative
/// to `root`. Empty for a directory that does not exist yet.
///
/// A file that cannot be read counts as a stranger, and so does a symlink:
/// both are cases where refusing costs a `--force` and proceeding could cost
/// someone's work.
fn strangers(root: &Path) -> Result<Vec<PathBuf>> {
    let mut out = vec![];
    if !root.exists() {
        return Ok(out);
    }

    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let entries =
            fs::read_dir(&dir).with_context(|| format!("Failed to read {}", dir.display()))?;
        for entry in entries {
            let entry = entry.with_context(|| format!("Failed to read {}", dir.display()))?;
            let path = entry.path();
            let file_type = entry
                .file_type()
                .with_context(|| format!("Failed to inspect {}", path.display()))?;

            if file_type.is_dir() {
                stack.push(path);
                continue;
            }
            if !marker_in(&fs::read(&path).unwrap_or_default()) {
                out.push(path.strip_prefix(root).unwrap_or(&path).to_path_buf());
            }
        }
    }

    out.sort();
    Ok(out)
}

/// Writes one plan, replacing the skill directory whole.
///
/// Built in a hidden sibling and renamed in, rather than written over the
/// existing tree, for two reasons. A crash halfway through an in-place write
/// leaves a skill that is half one version and half another, which an agent
/// will happily read. And a file we stopped generating would otherwise
/// survive forever, since nothing deletes it.
///
/// The old directory is moved aside rather than deleted first, so a failure
/// to rename the new one in can put it back.
fn apply(plan: &Plan) -> Result<()> {
    let root = plan.skill_dir();
    let parent = root
        .parent()
        .ok_or_else(|| anyhow!("{} has no parent directory", root.display()))?;

    fs::create_dir_all(parent).with_context(|| format!("Failed to create {}", parent.display()))?;

    let staging = parent.join(STAGING_DIR);
    let archive = parent.join(ARCHIVE_DIR);
    // Leftovers from a run that was killed between the renames below.
    let _ = fs::remove_dir_all(&staging);
    let _ = fs::remove_dir_all(&archive);

    write_tree(&staging, &plan.files)?;

    let existed = root.exists();
    if existed {
        fs::rename(&root, &archive).with_context(|| {
            format!(
                "Failed to move {} aside before replacing it",
                root.display()
            )
        })?;
    }

    if let Err(e) = fs::rename(&staging, &root) {
        if existed {
            let _ = fs::rename(&archive, &root);
        }
        let _ = fs::remove_dir_all(&staging);
        return Err(anyhow::Error::new(e).context(format!("Failed to write {}", root.display())));
    }

    if existed {
        let _ = fs::remove_dir_all(&archive);
    }
    Ok(())
}

/// The files, under a directory of their own.
///
/// `\n` line endings come from the rendering itself and are written as bytes,
/// so the same build produces the same files on every platform — a skill
/// generated on Windows and committed has to match one generated on Linux, or
/// the diff is noise.
fn write_tree(root: &Path, files: &[GeneratedFile]) -> Result<()> {
    for file in files {
        let path = root.join(&file.path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create {}", parent.display()))?;
        }
        fs::write(&path, file.contents.as_bytes())
            .with_context(|| format!("Failed to write {}", path.display()))?;
    }
    Ok(())
}

/// What was written, or what would have been.
fn report(mode: Mode, plans: &[Plan], dry_run: bool) -> Result<()> {
    let mut lines: Vec<String> = vec![];
    if dry_run {
        lines.push("Dry run — nothing was written.".to_string());
    }

    for plan in plans {
        let count = plan.files.len();
        lines.push(format!(
            "{} {count} file{} under {}:",
            if dry_run { "Would write" } else { "Wrote" },
            if count == 1 { "" } else { "s" },
            Destination {
                root: plan.skill_dir(),
                source: plan.destination.source.clone(),
            },
        ));
        for file in &plan.files {
            lines.push(format!("  {}", slashed(&file.path)));
        }
    }

    let json = json!({
        "dry_run": dry_run,
        "skill": SKILL_NAME,
        "destinations": plans
            .iter()
            .map(|plan| json!({
                "root": plan.skill_dir().display().to_string(),
                "source": plan.destination.source,
                "files": plan
                    .files
                    .iter()
                    .map(|file| slashed(&file.path))
                    .collect::<Vec<String>>(),
            }))
            .collect::<Vec<serde_json::Value>>(),
    });

    output::emit(mode, &lines.join("\n"), json)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn specs() -> Vec<ServiceSpec> {
        crate::spec::effective_services().expect("the bundled specs parse")
    }

    /// Everything a generated skill contains, for one build.
    fn generated() -> (Command, Vec<ServiceSpec>, Vec<GeneratedFile>) {
        let specs = specs();
        let app = crate::build_app(&specs);
        let schema = schema::build(&app, &specs, &[]);
        let header = Header::new(None);
        let files = render(&app, &schema, &header);
        (app, specs, files)
    }

    /// Every `mapbox …` line inside a ```sh block, across every file.
    fn examples(files: &[GeneratedFile]) -> Vec<String> {
        let mut out = vec![];
        for file in files {
            let mut inside = false;
            for line in file.contents.lines() {
                if line.starts_with("```") {
                    inside = line == "```sh";
                    continue;
                }
                if inside && line.starts_with("mapbox") {
                    out.push(line.to_string());
                }
            }
        }
        out
    }

    /// Whether `needle` appears in `haystack` as a whole word, treating `-`
    /// and `_` as part of a word.
    ///
    /// A plain `contains` would make the withheld-operation check answer
    /// yes for any name that is a prefix of an exposed one, and reporting a
    /// leak that is not there is how a guard gets deleted.
    fn mentions(haystack: &str, needle: &str) -> bool {
        let boundary =
            |c: Option<char>| c.is_none_or(|c| !c.is_alphanumeric() && c != '-' && c != '_');
        haystack.match_indices(needle).any(|(at, _)| {
            boundary(haystack[..at].chars().next_back())
                && boundary(haystack[at + needle.len()..].chars().next())
        })
    }

    /// **Guarantee 1.** Every example in the skill is a command line this CLI
    /// accepts.
    ///
    /// An example that does not parse is worse than no example: an agent will
    /// run it, get a usage error, and conclude the command is broken. So each
    /// one is handed back to the very tree it was derived from, through the
    /// same argv rewriting `main` applies — which matters for the proxy,
    /// whose arguments clap must not claim.
    #[test]
    fn every_generated_example_parses() {
        let (app, _, files) = generated();
        let examples = examples(&files);

        assert!(
            examples.len() > 20,
            "only {} examples found — the extraction is broken, and this test would \
             pass by checking nothing",
            examples.len()
        );

        for example in &examples {
            let argv: Vec<std::ffi::OsString> = split_example(example)
                .into_iter()
                .map(std::ffi::OsString::from)
                .collect();
            let argv = tilesets_cli::escape_passthrough_args(&app, argv);

            let parsed = app.clone().try_get_matches_from(&argv);
            assert!(
                parsed.is_ok(),
                "`{example}` is published as an example and does not parse: {}",
                parsed.err().map(|e| e.to_string()).unwrap_or_default()
            );
        }
    }

    /// **Guarantee 2.** Every command the CLI can run is described exactly
    /// once, and nothing else is.
    ///
    /// Both directions matter. A command missing from the skill is a command
    /// an agent will not use; a heading for something that is not a command
    /// sends it somewhere that answers as a typo does. Twice is its own bug —
    /// two descriptions drift.
    #[test]
    fn every_command_appears_in_exactly_one_generated_file() {
        let (app, _, files) = generated();

        let mut described: Vec<String> = vec![];
        for file in &files {
            for line in file.contents.lines() {
                if let Some(command) = line.strip_prefix("### ") {
                    described.push(command.to_string());
                }
            }
        }
        described.sort();

        // The same walk `schema::every_command_in_the_tree_is_described`
        // does, for the same reason: the command tree is the authority on
        // what a command is.
        let mut runnable = crate::runnable_commands(&app);
        runnable.sort();

        assert_eq!(described, runnable);

        let mut unique = described.clone();
        unique.dedup();
        assert_eq!(unique, described, "a command is described twice");
    }

    /// **Guarantee 3.** No operation the CLI withholds, disables or treats as
    /// a liveness probe is named anywhere in the skill.
    ///
    /// This is the property the whole design exists for. The skill is
    /// rendered from the schema, which applies `Operation::is_exposed`, so a
    /// leak here would mean the renderer had invented a name — but "cannot
    /// happen" is not a guarantee until something checks it, and a later
    /// change that reads the specs directly for one table would break it
    /// silently.
    #[test]
    fn no_operation_the_cli_withholds_is_named_anywhere() {
        let (_, specs, files) = generated();

        let forbidden: Vec<(String, String)> = specs
            .iter()
            .flat_map(|svc| svc.operations.iter().map(move |op| (svc, op)))
            .filter(|(_, op)| {
                op.is_withheld() || op.is_liveness_probe() || op.disabled_scope.is_some()
            })
            .map(|(svc, op)| (svc.name.clone(), op.command_path.join(" ")))
            .collect();
        // Legitimately empty now, not a broken guard: the maintainer-only
        // decision record strips every
        // `is_withheld`/`is_liveness_probe`/`disabled_scope` operation out
        // of the bundled specs entirely (rasterarrays' liveness probe
        // included, once it was given a real operationId to be `disabled`
        // by) — they're absent, not merely
        // filtered, which is a stronger guarantee than this loop could ever
        // check. Nothing left to assert on `forbidden.len()` itself; the
        // loop below still holds for whatever, if anything, shows up.

        for file in &files {
            for (service, command) in &forbidden {
                assert!(
                    !mentions(&file.contents, command),
                    "{} names `{service} {command}`, which is not a command",
                    file.path.display()
                );
                assert!(
                    !file
                        .contents
                        .contains(&format!("mapbox {service} {command}")),
                    "{} names `mapbox {service} {command}`, which is not a command",
                    file.path.display()
                );
            }
        }
    }

    /// **Guarantee 4, first half.** One build renders one skill.
    ///
    /// Rendered twice from two independently built trees, so a `HashMap`
    /// anywhere in the chain — or a stray timestamp — shows up here rather
    /// than as a spurious diff in whatever repository committed the output.
    #[test]
    fn two_renders_of_one_build_are_byte_identical() {
        let (_, _, first) = generated();
        let (_, _, second) = generated();
        assert_eq!(first, second);
    }

    /// Nothing in a generated file may vary with where or when it ran.
    #[test]
    fn nothing_generated_is_local_to_this_machine() {
        let (_, _, files) = generated();
        let home = dirs::home_dir().map(|home| home.display().to_string());

        for file in &files {
            assert!(
                !file.contents.contains(env!("CARGO_MANIFEST_DIR")),
                "{} names the directory it was built in",
                file.path.display()
            );
            if let Some(home) = &home {
                assert!(
                    !file.contents.contains(home.as_str()),
                    "{} names this machine's home directory",
                    file.path.display()
                );
            }
            assert!(
                !file.contents.contains('\r'),
                "{} has platform-dependent line endings",
                file.path.display()
            );
        }
    }

    /// Every file has to carry the marker, because the marker is what lets
    /// the next run replace the directory without asking.
    #[test]
    fn every_generated_file_says_it_was_generated() {
        let (_, _, files) = generated();
        assert!(files.len() > 3, "{} files", files.len());
        for file in &files {
            assert!(
                marker_in(file.contents.as_bytes()),
                "{} carries no generated marker in its first {MARKER_WINDOW} bytes",
                file.path.display()
            );
        }
    }

    /// SKILL.md's frontmatter has to be the first bytes of the file — the
    /// Agent Skills format reads it there and nowhere else — and it has to
    /// name the directory it sits in.
    #[test]
    fn the_skill_frontmatter_comes_first_and_names_the_skill() {
        let (_, _, files) = generated();
        let skill = files
            .iter()
            .find(|file| file.path == Path::new("SKILL.md"))
            .expect("SKILL.md is generated");

        assert!(
            skill.contents.starts_with("---\n"),
            "SKILL.md starts {:?}",
            &skill.contents[..skill.contents.len().min(40)]
        );
        let frontmatter = skill.contents[4..skill.contents[4..]
            .find("\n---\n")
            .expect("a closing fence")
            + 4]
            .to_string();
        assert!(
            frontmatter.contains(&format!("name: {SKILL_NAME}")),
            "{frontmatter}"
        );
        assert!(frontmatter.contains("description:"), "{frontmatter}");
    }

    /// Two documents that are supposed to say the same thing, and are written
    /// twice, say two things within a month.
    #[test]
    fn the_agents_md_and_skill_md_bodies_are_identical() {
        let header = Header::new(None);
        let body = "## Heading\n\nthe shared prose\n";

        let skill = render_skill_md(body, &header);
        let agents = render_agents_md(body, &header);

        assert!(skill.ends_with(body), "{skill}");
        assert!(agents.ends_with(body), "{agents}");

        // And through the real renderer, where a wrapper that swallowed part
        // of the body would still pass the two assertions above.
        let (app, specs, files) = generated();
        let schema = schema::build(&app, &specs, &[]);
        let real_body = render_body(&app, &schema, &by_service(&schema, &header), &header);
        for name in ["SKILL.md", "AGENTS.md"] {
            let file = files
                .iter()
                .find(|file| file.path == Path::new(name))
                .unwrap_or_else(|| panic!("{name} is generated"));
            assert!(
                file.contents.ends_with(&real_body),
                "{name} does not end with the shared body"
            );
        }
    }

    /// The precedence the skill publishes is the one the resolver applies,
    /// because it is read off the resolver.
    #[test]
    fn the_documented_token_precedence_is_the_resolvers() {
        use crate::auth::{resolve_source, TokenSource};

        let documented: Vec<TokenSource> = token_precedence()
            .iter()
            .map(|(source, _)| *source)
            .collect();

        // Each candidate withdrawn in turn: what wins next is the next rank.
        let resolved: Vec<TokenSource> = [
            resolve_source(Some("tk.flag"), Some("tk.env"), Some("tk.stored"), false),
            resolve_source(None, Some("tk.env"), Some("tk.stored"), false),
            resolve_source(None, None, Some("tk.stored"), false),
        ]
        .into_iter()
        .map(|outcome| outcome.expect("a candidate was available").0)
        .collect();

        assert_eq!(documented, resolved);

        // And the prose for each rank names the thing that rank is about, so
        // a reordering of the table cannot silently pass the check above.
        let prose: Vec<&str> = token_precedence().iter().map(|(_, text)| *text).collect();
        assert!(prose[0].contains("--token"), "{}", prose[0]);
        assert!(prose[1].contains("MAPBOX_ACCESS_TOKEN"), "{}", prose[1]);
        assert!(prose[2].contains("mapbox auth login"), "{}", prose[2]);
    }

    /// The skill body has to actually contain the cross-cutting sections —
    /// the half of the job `--schema` cannot do.
    #[test]
    fn the_skill_covers_what_a_schema_cannot() {
        let (_, _, files) = generated();
        let skill = &files
            .iter()
            .find(|file| file.path == Path::new("SKILL.md"))
            .expect("SKILL.md is generated")
            .contents;

        for section in [
            "## Authentication",
            "## The output contract",
            "## Errors",
            "## Dry runs",
            "## Describing a command as JSON",
            "## Command groups",
            "## Global options",
        ] {
            assert!(skill.contains(section), "SKILL.md has no {section}");
        }
        assert!(
            skill.contains(tilesets_cli::COMMAND),
            "SKILL.md does not mention the proxy"
        );
    }

    /// Every service gets a reference page, and every page belongs to a
    /// service — including the three hand-written ones, which is where the
    /// cross-cutting behaviour an agent trips over actually lives.
    #[test]
    fn every_service_has_a_reference_page() {
        let (_, _, files) = generated();

        let mut pages: Vec<String> = files
            .iter()
            .filter_map(|file| {
                file.path
                    .strip_prefix("references")
                    .ok()?
                    .to_str()?
                    .strip_suffix(".md")
                    .map(str::to_string)
            })
            .collect();
        pages.sort();

        assert!(
            pages.contains(&"auth".to_string()),
            "no auth reference: {pages:?}"
        );
        assert!(
            pages.contains(&tilesets_cli::COMMAND.to_string()),
            "no proxy reference: {pages:?}"
        );
        assert!(
            pages.contains(&COMMAND.to_string()),
            "no {COMMAND} reference: {pages:?}"
        );
    }

    /// `--service` narrows the skill and says so, rather than writing a
    /// partial skill that looks complete.
    #[test]
    fn a_service_filter_narrows_the_skill_and_is_recorded() {
        let specs = specs();
        let app = crate::build_app(&specs);
        let schema = schema::build(&app, &specs, &[]);

        let header = Header::new(Some(vec!["styles".to_string()]));
        let files = render(&app, &schema, &header);

        let pages: Vec<String> = files
            .iter()
            .filter(|file| file.path.starts_with("references"))
            .map(|file| slashed(&file.path))
            .collect();
        assert_eq!(pages, vec!["references/styles.md".to_string()]);

        for file in &files {
            assert!(
                file.contents.contains("command groups: styles"),
                "{} does not record the filter",
                file.path.display()
            );
        }

        // And with no filter, no such line — a complete skill must not look
        // like a narrowed one.
        let (_, _, whole) = generated();
        for file in &whole {
            assert!(
                !file.contents.contains("     command groups: "),
                "{} records a filter that was not applied",
                file.path.display()
            );
        }
    }

    /// An unknown `--service` is refused, and the refusal says what is valid.
    #[test]
    fn an_unknown_service_is_an_error_that_lists_the_real_ones() {
        let specs = specs();
        let app = crate::build_app(&specs);
        let schema = schema::build(&app, &specs, &[]);

        let matches = app
            .clone()
            .try_get_matches_from(["mapbox", COMMAND, "--service", "style"])
            .expect("the command line parses; the value is what is wrong");
        let sub = matches.subcommand_matches(COMMAND).expect("the subcommand");

        let err = requested_services(&schema, sub).expect_err("`style` is not a service");
        let message = err.to_string();
        assert!(message.contains("styles"), "{message}");
        assert!(message.contains('`'), "{message}");

        // A real one, twice, is one service.
        let matches = app
            .try_get_matches_from([
                "mapbox",
                COMMAND,
                "--service",
                "styles",
                "--service",
                "styles",
            ])
            .expect("repeating a service parses");
        let sub = matches.subcommand_matches(COMMAND).expect("the subcommand");
        assert_eq!(
            requested_services(&schema, sub).unwrap(),
            Some(vec!["styles".to_string()])
        );
    }

    /// The header records what a reader needs to tell a stale skill from a
    /// current one, and nothing that would make two runs differ.
    #[test]
    fn the_header_records_the_build_it_came_from() {
        let comment = Header::new(None).comment();
        assert!(
            comment.starts_with(&format!("<!-- {GENERATED_MARKER}")),
            "{comment}"
        );
        assert!(comment.ends_with("-->"), "{comment}");
        assert!(comment.contains(env!("CARGO_PKG_VERSION")), "{comment}");
        assert!(comment.contains(&spec_digest()), "{comment}");
        assert!(!comment.contains("     command groups:"), "{comment}");

        // The digest is stable within a build and depends on the specs.
        assert_eq!(spec_digest(), spec_digest());
        assert_eq!(spec_digest().len(), 12, "{}", spec_digest());
        assert!(spec_digest().chars().all(|c| c.is_ascii_hexdigit()));
    }

    /// The marker has to be found where it is written and nowhere it is not.
    #[test]
    fn the_marker_is_read_out_of_the_head_of_a_file() {
        assert!(marker_in(Header::new(None).comment().as_bytes()));
        assert!(!marker_in(b""));
        assert!(!marker_in(b"a hand-written note"));

        // Far enough down and it does not count: a document quoting this
        // command in its body has not agreed to be overwritten.
        let buried = format!("{}\n{GENERATED_MARKER}", "x".repeat(MARKER_WINDOW));
        assert!(!marker_in(buried.as_bytes()));

        // Invalid UTF-8 before the marker must not stop it being found, and
        // must not panic.
        let mut bytes = vec![0xff, 0xfe];
        bytes.extend_from_slice(GENERATED_MARKER.as_bytes());
        assert!(marker_in(&bytes));
    }

    /// The writer and the splitter are one pair, and the round trip is what
    /// every example depends on.
    #[test]
    fn a_quoted_word_survives_the_round_trip() {
        for value in ["plain", "", "{}", "with space", "a|b", "@2x", "-74.0"] {
            assert_eq!(
                split_example(&format!("mapbox x {}", shell_word(value))),
                vec!["mapbox".to_string(), "x".to_string(), value.to_string()],
                "{value:?} did not survive"
            );
        }

        // Whitespace runs collapse, and a quoted empty word is still a word.
        assert_eq!(split_example("  a   b  "), vec!["a", "b"]);
        assert_eq!(split_example("a '' b"), vec!["a", "", "b"]);
    }

    /// A heading inside spec prose must not be able to pass for a command
    /// heading — the geocoder's batch operation ships three of them.
    #[test]
    fn a_heading_in_spec_prose_is_demoted_below_the_command() {
        assert_eq!(demote_headings("# Top"), "#### Top");
        assert_eq!(
            demote_headings("### Example request"),
            "#### Example request"
        );
        assert_eq!(demote_headings("#### Already deep"), "#### Already deep");
        assert_eq!(
            demote_headings("###### Deeper still"),
            "###### Deeper still"
        );
        // Not a heading: no space after the hashes.
        assert_eq!(demote_headings("#hashtag"), "#hashtag");
        assert_eq!(demote_headings("plain prose"), "plain prose");

        // A `#` inside a fence is a comment or a colour, not a heading.
        let fenced = "```bash\n# curl it\n```\n### After";
        assert_eq!(
            fenced.replace("### After", "#### After"),
            demote_headings(fenced)
        );

        // And the real specs are the reason this exists.
        let (_, _, files) = generated();
        let geocoder = files
            .iter()
            .find(|file| file.path == Path::new("references").join("geocoder.md"))
            .expect("the geocoder reference");
        assert!(
            geocoder
                .contents
                .contains("#### Example request: Batch geocoding"),
            "the spec's own heading was not demoted"
        );
    }

    /// A cell that ends early takes the rest of the row's columns with it.
    #[test]
    fn a_table_cell_cannot_end_its_own_row() {
        assert_eq!(cell("a | b"), "a \\| b");
        assert_eq!(cell("two\nlines"), "two lines");
        assert_eq!(cell("  padded  out  "), "padded out");
        assert_eq!(code("a|b"), "`a\\|b`");
    }

    /// Positionals are identified by position, so their order is the
    /// contract; flags are not, so theirs is alphabetical and stays put when
    /// a spec grows a parameter.
    #[test]
    fn positionals_keep_their_order_and_flags_are_sorted() {
        let (_, specs, _) = generated();
        let app = crate::build_app(&specs);
        let schema = schema::build(&app, &specs, &[]);

        let mut checked = 0usize;
        for entry in &schema.commands {
            let ordered = ordered_arguments(entry);

            let declared: Vec<&String> = entry
                .arguments
                .iter()
                .filter(|arg| arg.kind == ArgKind::Positional)
                .map(|arg| &arg.name)
                .collect();
            let rendered: Vec<&String> = ordered
                .iter()
                .filter(|arg| arg.kind == ArgKind::Positional)
                .map(|arg| &arg.name)
                .collect();
            assert_eq!(rendered, declared, "{}", entry.command);

            let flags: Vec<String> = ordered
                .iter()
                .filter(|arg| arg.kind != ArgKind::Positional)
                .map(|arg| spelling(arg))
                .collect();
            let mut sorted = flags.clone();
            sorted.sort();
            assert_eq!(flags, sorted, "{}", entry.command);

            checked += usize::from(!ordered.is_empty());
        }
        assert!(checked > 20, "only {checked} commands have arguments");
    }

    /// A table shows a value as something to replace, and shows the short
    /// spelling of a flag that has one.
    #[test]
    fn a_table_names_a_value_rather_than_suggesting_one() {
        let (_, specs, files) = generated();
        let app = crate::build_app(&specs);
        let schema = schema::build(&app, &specs, &[]);

        let output = schema
            .global_options
            .iter()
            .find(|arg| arg.name == crate::output::ARG)
            .expect("--output is global");
        // Its accepted values belong in the Values column, not in the cell
        // that says how to write it.
        assert_eq!(written_as(output), "--output OUTPUT");
        assert_eq!(written_cell(output), "`--output OUTPUT` `-o`");
        assert!(values_cell(output).contains("`auto`"));
        // The example, by contrast, has to be something the parser accepts.
        assert_eq!(placeholder(output), crate::output::AUTO);

        // camelCase parameters read as placeholders rather than as one word.
        let image = schema
            .commands
            .iter()
            .find(|entry| entry.name == "get-static-image")
            .expect("get-static-image is a command");
        let high_res = image
            .arguments
            .iter()
            .find(|arg| arg.name == "highRes")
            .expect("it takes a resolution flag");
        assert_eq!(value_name(high_res), "HIGH_RES");

        // And every short spelling the globals declare reaches the reader.
        let skill = &files
            .iter()
            .find(|file| file.path == Path::new("SKILL.md"))
            .expect("SKILL.md is generated")
            .contents;
        for short in ["`-o`", "`-t`", "`-u`", "`-y`"] {
            assert!(skill.contains(short), "SKILL.md never mentions {short}");
        }
    }

    /// A line of clap help is kept whole; a spec paragraph is cut.
    ///
    /// The old rule cut everything at the first `.`, which turned
    /// `--output`'s help into "Output format." and dropped the half that says
    /// what the formats are.
    #[test]
    fn a_description_is_cut_only_when_it_would_not_fit() {
        let (_, specs, _) = generated();
        let app = crate::build_app(&specs);
        let schema = schema::build(&app, &specs, &[]);

        let output = schema
            .global_options
            .iter()
            .find(|arg| arg.name == crate::output::ARG)
            .expect("--output is global");
        let described = describe(output);
        assert!(
            described.contains("a terminal gets text"),
            "the whole of --output's help should survive: {described}"
        );

        // A spec paragraph does not fit, and says where the rest is.
        let types = schema
            .commands
            .iter()
            .flat_map(|entry| &entry.arguments)
            .find(|arg| {
                arg.description
                    .as_deref()
                    .is_some_and(|text| text.len() > CELL_BUDGET + 100)
            })
            .expect("some spec description is a long paragraph");
        let described = describe(types);
        assert!(
            described.len() < types.description.as_deref().unwrap_or_default().len(),
            "a long paragraph was not shortened"
        );

        // A cell is escaped exactly once, whichever branch produced it.
        assert!(!describe(types).contains("\\\\|"));
        assert_eq!(summarise("a | b"), "a \\| b");
        assert_eq!(summarise("one\ntwo"), "one two");

        // And a help string that already says "repeatable" does not say it
        // twice.
        let agent = schema
            .commands
            .iter()
            .find(|entry| entry.name == COMMAND)
            .expect("generate-skills is a command")
            .arguments
            .iter()
            .find(|arg| arg.name == crate::skill_dest::AGENT_ARG)
            .expect("it takes --agent");
        assert!(agent.repeatable);
        assert_eq!(
            describe(agent).to_lowercase().matches("repeatable").count(),
            1,
            "{}",
            describe(agent)
        );

        // Same for the multipart field, which `--file`'s help already names.
        let sprite = schema
            .commands
            .iter()
            .find(|entry| entry.name == "upload-batch")
            .expect("sprites upload-batch is a command")
            .arguments
            .iter()
            .find(|arg| arg.multipart_field.is_some())
            .expect("it uploads multipart files");
        let field = sprite.multipart_field.as_deref().expect("a field name");
        assert_eq!(
            describe(sprite).matches(&format!("`{field}`")).count(),
            1,
            "{}",
            describe(sprite)
        );
    }

    /// A command that is its own service must not have its one sentence
    /// printed three times.
    #[test]
    fn a_single_command_service_says_its_summary_once() {
        let (_, _, files) = generated();

        for service in [COMMAND, tilesets_cli::COMMAND] {
            let page = files
                .iter()
                .find(|file| file.path == Path::new("references").join(format!("{service}.md")))
                .unwrap_or_else(|| panic!("{service} has a reference page"));

            // The page heading, then straight to the command — no service
            // intro repeating what the command's own block says.
            let summary_line = page.contents.lines().find(|line| {
                line.starts_with("Write Agent Skills") || line.starts_with("Proxy commands")
            });
            if let Some(summary) = summary_line {
                assert_eq!(
                    page.contents.matches(summary).count(),
                    1,
                    "{service}.md repeats {summary:?}"
                );
            }
        }

        // A service with real operations still gets its own intro, which is a
        // different sentence from any command's.
        let styles = files
            .iter()
            .find(|file| file.path == Path::new("references").join("styles.md"))
            .expect("styles has a reference page");
        assert!(
            styles.contents.contains("Mapbox Styles API"),
            "styles.md lost its service intro"
        );
    }

    /// A directory holding someone else's file is refused, named, and left
    /// alone until `--force`.
    #[test]
    fn a_directory_we_did_not_write_is_refused_by_name() {
        let root = std::env::temp_dir().join("mapbox-cli-generate-skills-stranger");
        let skill = root.join(SKILL_NAME);
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(skill.join("references")).expect("create the skill dir");

        let destination = Destination {
            root: root.clone(),
            source: None,
        };
        let files = vec![GeneratedFile {
            path: PathBuf::from("SKILL.md"),
            contents: format!("{}\n", Header::new(None).comment()),
        }];

        // Ours: every file carries the marker.
        fs::write(
            skill.join("SKILL.md"),
            format!("{}\n", Header::new(None).comment()),
        )
        .expect("write a generated file");
        assert!(strangers(&skill).unwrap().is_empty());
        assert!(plan(destination.clone(), files.clone(), false).is_ok());

        // And not ours the moment anything else is in there, however deep.
        fs::write(skill.join("references").join("notes.md"), "mine\n").expect("write a stranger");
        assert_eq!(
            strangers(&skill).unwrap(),
            vec![PathBuf::from("references").join("notes.md")]
        );

        let err =
            plan(destination.clone(), files.clone(), false).expect_err("a stranger is present");
        let message = err.to_string();
        assert!(message.contains("notes.md"), "{message}");
        assert!(message.contains("--force"), "{message}");

        assert!(
            plan(destination, files, true).is_ok(),
            "--force has to get past it"
        );

        let _ = fs::remove_dir_all(&root);
    }

    /// A write replaces the directory whole: a file we no longer generate has
    /// to go, or it outlives the command that made it forever.
    #[test]
    fn a_write_replaces_the_directory_rather_than_merging_into_it() {
        let root = std::env::temp_dir().join("mapbox-cli-generate-skills-replace");
        let _ = fs::remove_dir_all(&root);

        let marker = format!("{}\n", Header::new(None).comment());
        let stale = Plan {
            destination: Destination {
                root: root.clone(),
                source: None,
            },
            files: vec![
                GeneratedFile {
                    path: PathBuf::from("SKILL.md"),
                    contents: marker.clone(),
                },
                GeneratedFile {
                    path: PathBuf::from("references").join("gone.md"),
                    contents: marker.clone(),
                },
            ],
        };
        apply(&stale).expect("first write");
        assert!(root.join(SKILL_NAME).join("references/gone.md").exists());

        let fresh = Plan {
            destination: stale.destination,
            files: vec![GeneratedFile {
                path: PathBuf::from("SKILL.md"),
                contents: marker,
            }],
        };
        apply(&fresh).expect("second write");
        assert!(root.join(SKILL_NAME).join("SKILL.md").exists());
        assert!(
            !root.join(SKILL_NAME).join("references/gone.md").exists(),
            "a file we stopped generating survived"
        );
        // Neither working directory is left behind.
        assert!(!root.join(STAGING_DIR).exists());
        assert!(!root.join(ARCHIVE_DIR).exists());

        let _ = fs::remove_dir_all(&root);
    }
}
